apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "legend.fullname" . }}
  namespace: {{ include "legend.namespace" . }}
  labels:
    {{- include "legend.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: legend
      {{- include "legend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: legend
        {{- include "legend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "legend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GRAFANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "legend.secretsName" . }}
                  key: api_key
            - name: GRAFANA_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "legend.secretsName" . }}
                  key: host
            - name: GRAFANA_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: {{ include "legend.secretsName" . }}
                  key: protocol
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "legend.secretsName" . }}
                  key: sentry_dsn
            - name: SENTRY_ENVRIONMENT
              valueFrom:
                secretKeyRef:
                  name: {{ include "legend.secretsName" . }}
                  key: sentry_environment
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

